import React from 'react';
import { BrowserRouter, Routes, Route } from 'react-router-dom';
import MainLayout from './layouts/MainLayout';
import Dashboard from './pages/Dashboard';
import './App.css';

// Placeholder empty states for new enterprise pages
const PlaceholderPage = ({ title, subtitle }) => (
  <div style={{ padding: '2rem', display: 'flex', flexDirection: 'column', height: '100%', alignItems: 'center', justifyContent: 'center', color: 'var(--text-muted)' }}>
    <h2 style={{ color: '#fff', marginBottom: '0.5rem' }}>{title}</h2>
    <p>{subtitle}</p>
    <div style={{ marginTop: '2rem', padding: '2rem', border: '1px dashed var(--glass-border)', borderRadius: '8px', background: 'rgba(255,255,255,0.02)' }}>
      Module initializing... UI components loading for full production deployment.
    </div>
  </div>
);

function App() {
  return (
    <BrowserRouter>
      <Routes>
        <Route path="/" element={<MainLayout />}>
          <Route index element={<Dashboard />} />
          <Route path="assets" element={<PlaceholderPage title="Industrial Asset Hierarchy" subtitle="Drill down from Site -> Plant -> Line -> Machine. View real-time telemetry." />} />
          <Route path="maintenance" element={<PlaceholderPage title="Maintenance Workflow" subtitle="Manage Work Orders generated by AI, track assigning, severity, and resolution." />} />
          <Route path="ai-studio" element={<PlaceholderPage title="Multi-Agent AI Studio" subtitle="Orchestrate and inspect LangGraph-style AI workflows and reasoning traces." />} />
          <Route path="esg" element={<PlaceholderPage title="ESG & Compliance Desk" subtitle="Autogenerate ISSB / EU-ETS / Scope 1-3 reports from machine telemetry." />} />
          <Route path="history" element={<PlaceholderPage title="Audit Trail" subtitle="Verifiable logs of all system changes and AI actions." />} />
          <Route path="security" element={<PlaceholderPage title="Access & Security" subtitle="Role-based access control (RBAC) across Plant Manager, Engineer, and ESG Officer roles." />} />
        </Route>
      </Routes>
    </BrowserRouter>
  );
}

export default App;
