/**
 * CarbonOps Enterprise Industrial OS
 * 
 * Capability: Main Application Router & Identity Wrapper
 * Version: 1.1.0 (LTS Production Launch)
 * Architecture: Clean Code Module Indexing
 * Owner: Puneet Divedi
 */
import React from 'react';
import { BrowserRouter, Routes, Route, Navigate } from 'react-router-dom';
import MainLayout from './layouts/MainLayout';
import Dashboard from './pages/Dashboard';
import Login from './pages/Login';
import AssetsView from './pages/AssetsView';
import EsgReports from './pages/EsgReports';
import AiStudio from './pages/AiStudio';
import { AuthProvider, useAuth } from './context/AuthContext';
import { Toaster } from 'react-hot-toast';
import './App.css';

// Placeholder empty states for new enterprise pages
const PlaceholderPage = ({ title, subtitle }) => (
  <div style={{ padding: '2rem', display: 'flex', flexDirection: 'column', height: '100%', alignItems: 'center', justifyContent: 'center', color: 'var(--text-muted)' }}>
    <h2 style={{ color: '#fff', marginBottom: '0.5rem' }}>{title}</h2>
    <p>{subtitle}</p>
    <div style={{ marginTop: '2rem', padding: '2rem', border: '1px dashed var(--glass-border)', borderRadius: '8px', background: 'rgba(255,255,255,0.02)' }}>
      Module initializing... API endpoints under construction.
    </div>
  </div>
);

// Protected Auth Guard Component representing absolute scalable security.
const AppRoutes = () => {
  const { user } = useAuth();
  
  if (!user) {
    return <Login />; // Force unauthorized state to IAM wall
  }

  return (
    <Routes>
      <Route path="/" element={<MainLayout />}>
        <Route index element={<Dashboard />} />
        <Route path="assets" element={<AssetsView />} />
        <Route path="maintenance" element={<PlaceholderPage title="Maintenance Workflow" subtitle="Manage Work Orders generated by AI via the /api/v1/workorders LangGraph hook." />} />
        <Route path="ai-studio" element={<AiStudio />} />
        <Route path="esg" element={<EsgReports />} />
        <Route path="history" element={<PlaceholderPage title="Audit Trail" subtitle="Verifiable blockchain & DB logs of all Agent actions." />} />
        <Route path="security" element={<PlaceholderPage title="Access & Security" subtitle="Role-based access control (RBAC) across Plant Manager, Engineer, and ESG Officer roles." />} />
      </Route>
      <Route path="*" element={<Navigate to="/" replace />} />
    </Routes>
  );
};

// Root provider initialization
function App() {
  return (
    <BrowserRouter>
      {/* 
        PRODUCTION ENHANCEMENT: Wrapping the entire router tree in AuthProvider 
        ensures the SSO context is globally inherited, discarding complex prop logic 
      */}
      <AuthProvider>
        <Toaster 
          position="top-right" 
          toastOptions={{ style: { background: '#1c1c24', color: '#fff', border: '1px solid rgba(255,255,255,0.1)' } }} 
        />
        <AppRoutes />
      </AuthProvider>
    </BrowserRouter>
  );
}

export default App;
